name: 🚀 Chess Puzzle Solver - Deploy to Cloud Run

on:
  push:
    branches: [main]
    paths:
      - 'ChessPuzzleSolver/**'

env:
  PROJECT_ID: idyllic-parser-460423-r0
  WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
  SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        workload_identity_provider: projects/674748941743/locations/global/workloadIdentityPools/github-pool/providers/github-actions-provider
        service_account: github-actions@idyllic-parser-460423-r0.iam.gserviceaccount.com
        project_id: idyllic-parser-460423-r0
        create_credentials_file: true
        token_format: access_token
        audience: https://token.actions.githubusercontent.com  # Añade esta línea

    
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: idyllic-parser-460423-r0
        export_default_credentials: true

    - name: Build and push Docker image
      run: |-
      # Configura el host de Docker para Artifact Registry
      echo "Configurando Docker para Artifact Registry..."
      gcloud auth configure-docker us-docker.pkg.dev
      
      # Navega al directorio correcto
      cd ChessPuzzleSolver
      
      # Construye la imagen
      echo "Construyendo la imagen Docker..."
      docker build -t us-docker.pkg.dev/idyllic-parser-460423-r0/gcr.io/chesspuzzlesolver:${{ github.sha }} .
      
      # Sube la imagen
      echo "Subiendo la imagen a Artifact Registry..."
      docker push us-docker.pkg.dev/idyllic-parser-460423-r0/gcr.io/chesspuzzlesolver:${{ github.sha }}